"""Generate lunch-web-app/backend/cached_menus.py from normalized JSON input."""

from __future__ import annotations

import argparse
import json
import re
from decimal import Decimal
from pathlib import Path


def _constant_name(restaurant_name: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9]+", "_", restaurant_name.upper()).strip("_")
    if not cleaned:
        cleaned = "RESTAURANT"
    return f"{cleaned}_ITEMS"


def _price_literal(value: object) -> str:
    if value is None:
        return "None"

    # Keep integer prices compact, but preserve decimal precision when present.
    dec = Decimal(str(value))
    if dec == dec.to_integral_value():
        return str(int(dec))
    return f'Decimal("{dec}")'


def _item_sort_key(item: dict) -> tuple[str, str, str, str]:
    category = str(item.get("category") or "other")
    subcategory = str(item.get("subcategory") or "")
    name = str(item.get("name") or "")
    price = "" if item.get("price") is None else str(item.get("price"))
    return (category.lower(), subcategory.lower(), name.lower(), price)


def _render_item(item: dict, indent: str) -> list[str]:
    lines = [f"{indent}MenuItem("]
    lines.append(f"{indent}    name={json.dumps(str(item.get('name') or ''))},")

    price_value = item.get("price")
    lines.append(f"{indent}    price={_price_literal(price_value)},")

    category = str(item.get("category") or "other")
    lines.append(f"{indent}    category={json.dumps(category)},")

    subcategory = item.get("subcategory")
    if subcategory is not None and str(subcategory).strip():
        lines.append(f"{indent}    subcategory={json.dumps(str(subcategory))},")

    description = str(item.get("description") or "")
    lines.append(f"{indent}    description={json.dumps(description)},")
    lines.append(f"{indent}),")
    return lines


def generate_cached_menus(input_json: Path, output_py: Path) -> None:
    data = json.loads(input_json.read_text(encoding="utf-8"))
    restaurants = data.get("restaurants", [])

    needs_decimal = False
    for restaurant in restaurants:
        for item in restaurant.get("items", []):
            price = item.get("price")
            if price is not None and Decimal(str(price)) != Decimal(str(price)).to_integral_value():
                needs_decimal = True
                break

    lines: list[str] = []
    lines.append('"""Pre-scraped menus generated by scripts/generate_cached_menus.py."""')
    lines.append("")
    lines.append("from __future__ import annotations")
    lines.append("")
    if needs_decimal:
        lines.append("from decimal import Decimal")
    lines.append("from .models import MenuItem")
    lines.append("")

    restaurant_entries: list[tuple[str, str]] = []

    for restaurant in restaurants:
        name = str(restaurant.get("restaurant_name") or "")
        items = sorted(restaurant.get("items", []), key=_item_sort_key)
        const_name = _constant_name(name)
        restaurant_entries.append((name, const_name))

        lines.append(f"{const_name}: list[MenuItem] = [")
        for item in items:
            lines.extend(_render_item(item, "    "))
        lines.append("]")
        lines.append("")

    lines.append("CACHED_RESTAURANTS: list[dict] = [")
    for restaurant_name, const_name in restaurant_entries:
        lines.append("    {")
        lines.append(f"        \"restaurant_name\": {json.dumps(restaurant_name)},")
        lines.append(f"        \"items\": {const_name},")
        lines.append("    },")
    lines.append("]")
    lines.append("")

    output_py.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate cached_menus.py from JSON data")
    parser.add_argument(
        "--input",
        default=".menu-artifacts/menus_canonical.json",
        help="Path to normalized JSON input",
    )
    parser.add_argument(
        "--output",
        default="lunch-web-app/backend/cached_menus.py",
        help="Path to generated cached_menus.py",
    )
    args = parser.parse_args()

    generate_cached_menus(Path(args.input), Path(args.output))


if __name__ == "__main__":
    main()
